2020-11-18 17:06:39.690 | INFO     | __main__:serve:85 - ��������: 192.168.0.103:65093
2020-11-18 17:06:39.694 | INFO     | __main__:serve:88 - ����ע�Ὺʼ
2020-11-18 17:06:39.699 | INFO     | __main__:serve:95 - ����ע��ɹ�
2020-11-18 17:07:06.272 | ERROR    | grpc._server:_call_behavior:435 - An error has been caught in function '_call_behavior', process 'MainProcess' (89508), thread 'ThreadPoolExecutor-0_0' (96024):
Traceback (most recent call last):

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    ��    �� <function Thread._bootstrap_inner at 0x0000021E29BC2DC0>
    �� <Thread(ThreadPoolExecutor-0_0, started daemon 96024)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 932, in _bootstrap_inner
    self.run()
    ��    �� <function Thread.run at 0x0000021E29BC2AF0>
    �� <Thread(ThreadPoolExecutor-0_0, started daemon 96024)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    ��    ��        ��    ��        ��    �� {}
    ��    ��        ��    ��        �� <Thread(ThreadPoolExecutor-0_0, started daemon 96024)>
    ��    ��        ��    �� (<weakref at 0x0000021E2BD8C270; to 'ThreadPoolExecutor' at 0x0000021E2BC01F10>, <_queue.SimpleQueue object at 0x0000021E2BC1...
    ��    ��        �� <Thread(ThreadPoolExecutor-0_0, started daemon 96024)>
    ��    �� <function _worker at 0x0000021E2BC12820>
    �� <Thread(ThreadPoolExecutor-0_0, started daemon 96024)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
    ��         �� <function _WorkItem.run at 0x0000021E2BC12940>
    �� <concurrent.futures.thread._WorkItem object at 0x0000021E2BC6AAC0>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             ��    ��   ��    ��       ��    �� {}
             ��    ��   ��    ��       �� <concurrent.futures.thread._WorkItem object at 0x0000021E2BC6AAC0>
             ��    ��   ��    �� [<grpc._cython.cygrpc.RequestCallEvent object at 0x0000021E2A93D360>, <grpc._server._RPCState object at 0x0000021E2BD8F1C0>, ...
             ��    ��   �� <concurrent.futures.thread._WorkItem object at 0x0000021E2BC6AAC0>
             ��    �� <function _unary_response_in_pool at 0x0000021E2BC51310>
             �� <concurrent.futures.thread._WorkItem object at 0x0000021E2BC6AAC0>

  File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 552, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        ��              ��          ��      �� <bound method OrderServicer.CreateOrder of <userop_srv.handler.order.OrderServicer object at 0x0000021E2BC287C0>>
                        ��              ��          �� <grpc._server._RPCState object at 0x0000021E2BD8F1C0>
                        ��              �� <grpc._cython.cygrpc.RequestCallEvent object at 0x0000021E2A93D360>
                        �� <function _call_behavior at 0x0000021E2BC4FEE0>

> File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           ��        ��         �� <grpc._server._Context object at 0x0000021E2BE375B0>
                           ��        �� userId: 1
                           ��          address: "\345\214\227\344\272\254\345\270\202"
                           ��          mobile: "18787878787"
                           ��          name: "bobby"
                           ��          post: "\350\257\267\345\260\275...
                           �� <bound method OrderServicer.CreateOrder of <userop_srv.handler.order.OrderServicer object at 0x0000021E2BC287C0>>

  File "C:\Users\Administrator\PycharmProjects\mxshop_srvs\userop_srv\handler\order.py", line 191, in CreateOrder
    goods_srv_host, goods_srv_port = register.get_host_port(f'Service=="{settings.GOODS_SRV_NAME}"')
                                     ��        �� <function ConsulRegister.get_host_port at 0x0000021E2B36E790>
                                     �� <common.register.consul.ConsulRegister object at 0x0000021E2BE37FA0>

  File "C:\Users\Administrator\PycharmProjects\mxshop_srvs\common\register\consul.py", line 50, in get_host_port
    return service_info["Address"], service_info["Port"]
           ��                        �� [{'ID': '6b3d3373-297d-11eb-af55-40b0760ebfa7', 'Service': 'goods-srv', 'Tags': ['imooc', 'bobby', 'python', 'srv'], 'Meta': ...
           �� [{'ID': '6b3d3373-297d-11eb-af55-40b0760ebfa7', 'Service': 'goods-srv', 'Tags': ['imooc', 'bobby', 'python', 'srv'], 'Meta': ...

TypeError: list indices must be integers or slices, not str
2020-11-18 17:08:17.263 | INFO     | __main__:on_exit:26 - ע�� 5e6ed0f2-297d-11eb-9886-40b0760ebfa7 ����
2020-11-18 17:08:17.267 | INFO     | __main__:on_exit:28 - ע���ɹ�
