2020-11-19 11:58:11.782 | INFO     | __main__:serve:85 - 启动服务: 192.168.0.103:52174
2020-11-19 11:58:11.787 | INFO     | __main__:serve:88 - 服务注册开始
2020-11-19 11:58:11.792 | INFO     | __main__:serve:95 - 服务注册成功
2020-11-19 11:58:15.547 | ERROR    | grpc._server:_call_behavior:435 - An error has been caught in function '_call_behavior', process 'MainProcess' (61464), thread 'ThreadPoolExecutor-0_0' (75920):
Traceback (most recent call last):

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001C540982DC0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 75920)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000001C540982AF0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 75920)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 75920)>
    │    │        │    └ (<weakref at 0x000001C542B464A0; to 'ThreadPoolExecutor' at 0x000001C5429D4400>, <_queue.SimpleQueue object at 0x000001C5429D...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 75920)>
    │    └ <function _worker at 0x000001C5429CCB80>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 75920)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x000001C5429CCCA0>
    └ <concurrent.futures.thread._WorkItem object at 0x000001C542B44160>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000001C542B44160>
             │    │   │    └ [<grpc._cython.cygrpc.RequestCallEvent object at 0x000001C5416FD360>, <grpc._server._RPCState object at 0x000001C542A27430>, ...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000001C542B44160>
             │    └ <function _unary_response_in_pool at 0x000001C542A10670>
             └ <concurrent.futures.thread._WorkItem object at 0x000001C542B44160>

  File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 552, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.OrderDetail of <order_srv.handler.order.OrderServicer object at 0x000001C5429E6BB0>>
                        │              │          └ <grpc._server._RPCState object at 0x000001C542A27430>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x000001C5416FD360>
                        └ <function _call_behavior at 0x000001C542A10280>

> File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x000001C542B444C0>
                           │        └ id: 4
                           │          
                           └ <bound method OrderServicer.OrderDetail of <order_srv.handler.order.OrderServicer object at 0x000001C5429E6BB0>>

  File "C:\Users\Administrator\PycharmProjects\mxshop_srvs\order_srv\handler\order.py", line 156, in OrderDetail
    rsp.goods.append(order_goods_rsp)
    │                └ goodsId: 421
    │                  goodsName: "\347\203\237\345\217\260\347\272\242\345\257\214\345\243\253\350\213\271\346\236\23412\344\270\252 \...
    └ orderInfo {
        id: 4
        userId: 1
        orderSn: "20201118171410162"
        payType: "alipay"
        status: "paying"
        post: "\350\257\267\3...

AttributeError: 'OrderInfoDetailResponse' object has no attribute 'goods'
2020-11-19 11:58:32.935 | INFO     | __main__:on_exit:26 - 注销 7145ecbb-2a1b-11eb-a8b7-40b0760ebfa7 服务
2020-11-19 11:58:32.939 | INFO     | __main__:on_exit:28 - 注销成功
