2020-11-19 13:43:27.054 | INFO     | __main__:serve:85 - 启动服务: 192.168.0.103:56440
2020-11-19 13:43:27.057 | INFO     | __main__:serve:88 - 服务注册开始
2020-11-19 13:43:27.062 | INFO     | __main__:serve:95 - 服务注册成功
2020-11-19 22:42:28.202 | ERROR    | grpc._server:_call_behavior:435 - An error has been caught in function '_call_behavior', process 'MainProcess' (23616), thread 'ThreadPoolExecutor-0_0' (76556):
Traceback (most recent call last):

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001E5B6962DC0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 76556)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000001E5B6962AF0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 76556)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 76556)>
    │    │        │    └ (<weakref at 0x000001E5B8B26450; to 'ThreadPoolExecutor' at 0x000001E5B89B3400>, <_queue.SimpleQueue object at 0x000001E5B89B...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 76556)>
    │    └ <function _worker at 0x000001E5B89ACB80>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 76556)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x000001E5B89ACCA0>
    └ <concurrent.futures.thread._WorkItem object at 0x000001E5B8D9C040>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000001E5B8D9C040>
             │    │   │    └ [<grpc._cython.cygrpc.RequestCallEvent object at 0x000001E5B8B26630>, <grpc._server._RPCState object at 0x000001E5B8DA2DC0>, ...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000001E5B8D9C040>
             │    └ <function _unary_response_in_pool at 0x000001E5B89F0670>
             └ <concurrent.futures.thread._WorkItem object at 0x000001E5B8D9C040>

  File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 552, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.UpdateOrderStatus of <order_srv.handler.order.OrderServicer object at 0x000001E5B89C8CD0>>
                        │              │          └ <grpc._server._RPCState object at 0x000001E5B8DA2DC0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x000001E5B8B26630>
                        └ <function _call_behavior at 0x000001E5B89F0280>

> File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x000001E5B8D9CEE0>
                           │        └ OrderSn: "20201119224057124"
                           │          status: "TRADE_SUCCESS"
                           │          
                           └ <bound method OrderServicer.UpdateOrderStatus of <order_srv.handler.order.OrderServicer object at 0x000001E5B89C8CD0>>

  File "C:\Users\Administrator\PycharmProjects\mxshop_srvs\order_srv\handler\order.py", line 167, in UpdateOrderStatus
    OrderInfo.update(status=request.status).where(OrderInfo.order_sn == request.orderSn)
    │         │             │       │             │         │           └ OrderSn: "20201119224057124"
    │         │             │       │             │         │             status: "TRADE_SUCCESS"
    │         │             │       │             │         │             
    │         │             │       │             │         └ <peewee.FieldAccessor object at 0x000001E5B7C6DAC0>
    │         │             │       │             └ <Model: OrderInfo>
    │         │             │       └ <google.protobuf.internal.python_message._FieldProperty object at 0x000001E5B78581D0>
    │         │             └ OrderSn: "20201119224057124"
    │         │               status: "TRADE_SUCCESS"
    │         │               
    │         └ <classmethod object at 0x000001E5B7A3B190>
    └ <Model: OrderInfo>

AttributeError: 'OrderStatus' object has no attribute 'orderSn'
