2020-11-19 11:45:55.817 | INFO     | __main__:serve:85 - 启动服务: 192.168.0.103:51782
2020-11-19 11:45:55.821 | INFO     | __main__:serve:88 - 服务注册开始
2020-11-19 11:45:55.827 | INFO     | __main__:serve:95 - 服务注册成功
2020-11-19 11:55:41.170 | ERROR    | grpc._server:_call_behavior:435 - An error has been caught in function '_call_behavior', process 'MainProcess' (70784), thread 'ThreadPoolExecutor-0_0' (92500):
Traceback (most recent call last):

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001E7CADD2DC0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 92500)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000001E7CADD2AF0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 92500)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 92500)>
    │    │        │    └ (<weakref at 0x000001E7CCF8B3B0; to 'ThreadPoolExecutor' at 0x000001E7CCE14460>, <_queue.SimpleQueue object at 0x000001E7CCE1...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 92500)>
    │    └ <function _worker at 0x000001E7CCE0CCA0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 92500)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x000001E7CCE0CDC0>
    └ <concurrent.futures.thread._WorkItem object at 0x000001E7CD1821F0>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000001E7CD1821F0>
             │    │   │    └ [<grpc._cython.cygrpc.RequestCallEvent object at 0x000001E7CD02FEF0>, <grpc._server._RPCState object at 0x000001E7CD03EEE0>, ...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000001E7CD1821F0>
             │    └ <function _unary_response_in_pool at 0x000001E7CCE51670>
             └ <concurrent.futures.thread._WorkItem object at 0x000001E7CD1821F0>

  File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 552, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.OrderDetail of <order_srv.handler.order.OrderServicer object at 0x000001E7CCE28CD0>>
                        │              │          └ <grpc._server._RPCState object at 0x000001E7CD03EEE0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x000001E7CD02FEF0>
                        └ <function _call_behavior at 0x000001E7CCE51280>

> File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x000001E7CD182370>
                           │        └ id: 4
                           │          
                           └ <bound method OrderServicer.OrderDetail of <order_srv.handler.order.OrderServicer object at 0x000001E7CCE28CD0>>

  File "C:\Users\Administrator\PycharmProjects\mxshop_srvs\order_srv\handler\order.py", line 144, in OrderDetail
    rsp.orderInfo.mobile = order.signer_mobile
    │   │                  └ <OrderInfo: 4>
    │   └ <google.protobuf.internal.python_message._FieldProperty object at 0x000001E7CBCBDD60>
    └ orderInfo {
        id: 4
        userId: 1
        orderSn: "20201118171410162"
        payType: "alipay"
        status: "paying"
        post: "\350\257\267\3...

AttributeError: 'OrderInfo' object has no attribute 'signer_mobile'
2020-11-19 11:57:00.498 | INFO     | __main__:on_exit:26 - 注销 ba9a91f5-2a19-11eb-8569-40b0760ebfa7 服务
2020-11-19 11:57:00.526 | INFO     | __main__:on_exit:28 - 注销成功
