2020-09-30 20:40:57.566 | INFO     | __main__:serve:85 - 启动服务: 192.168.1.102:59040
2020-09-30 20:40:57.570 | INFO     | __main__:serve:88 - 服务注册开始
2020-09-30 20:40:57.575 | INFO     | __main__:serve:95 - 服务注册成功
2020-09-30 20:41:04.002 | ERROR    | grpc._server:_call_behavior:435 - An error has been caught in function '_call_behavior', process 'MainProcess' (43820), thread 'ThreadPoolExecutor-0_0' (40092):
Traceback (most recent call last):

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x00000276A9F62DC0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 40092)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x00000276A9F62AF0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 40092)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 40092)>
    │    │        │    └ (<weakref at 0x00000276AC10A1D0; to 'ThreadPoolExecutor' at 0x00000276ABE97310>, <_queue.SimpleQueue object at 0x00000276ABE9...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 40092)>
    │    └ <function _worker at 0x00000276ABE9F160>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 40092)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x00000276ABE9F280>
    └ <concurrent.futures.thread._WorkItem object at 0x00000276ABEE7A30>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x00000276ABEE7A30>
             │    │   │    └ [<grpc._cython.cygrpc.RequestCallEvent object at 0x00000276AACEA7C0>, <grpc._server._RPCState object at 0x00000276ABEDFF70>, ...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x00000276ABEE7A30>
             │    └ <function _unary_response_in_pool at 0x00000276ABECCAF0>
             └ <concurrent.futures.thread._WorkItem object at 0x00000276ABEE7A30>

  File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 552, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method GoodsServicer.BatchGetGoods of <goods_srv.handler.goods.GoodsServicer object at 0x00000276ABEA5880>>
                        │              │          └ <grpc._server._RPCState object at 0x00000276ABEDFF70>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x00000276AACEA7C0>
                        └ <function _call_behavior at 0x00000276ABECC700>

> File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x00000276AC10F0D0>
                           │        └ id: 421
                           │          id: 422
                           │          
                           └ <bound method GoodsServicer.BatchGetGoods of <goods_srv.handler.goods.GoodsServicer object at 0x00000276ABEA5880>>

  File "C:\Users\Administrator\PycharmProjects\mxshop_srvs\goods_srv\handler\goods.py", line 100, in BatchGetGoods
    goods = Goods.where(Goods.id.in_(list(request.id)))
            │           │     │           │       └ <google.protobuf.internal.python_message._FieldProperty object at 0x00000276AAE8EE50>
            │           │     │           └ id: 421
            │           │     │             id: 422
            │           │     │             
            │           │     └ <peewee.FieldAccessor object at 0x00000276AB1100D0>
            │           └ <Model: Goods>
            └ <Model: Goods>

AttributeError: type object 'Goods' has no attribute 'where'
2020-09-30 20:41:13.330 | INFO     | __main__:on_exit:26 - 注销 3015349e-031a-11eb-abf4-40b0760ebfa7 服务
2020-09-30 20:41:13.340 | INFO     | __main__:on_exit:28 - 注销成功
