2020-09-30 23:58:08.726 | INFO     | __main__:serve:87 - 启动服务: 192.168.1.102:57245
2020-09-30 23:58:08.730 | INFO     | __main__:serve:90 - 服务注册开始
2020-09-30 23:58:08.735 | INFO     | __main__:serve:97 - 服务注册成功
2020-09-30 23:58:13.282 | ERROR    | grpc._server:_call_behavior:435 - An error has been caught in function '_call_behavior', process 'MainProcess' (33672), thread 'ThreadPoolExecutor-0_0' (46504):
Traceback (most recent call last):

  File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\google\protobuf\internal\python_message.py", line 713, in field_setter
    new_value = type_checker.CheckValue(new_value)
                │            │          └ None
                │            └ <function IntValueChecker.CheckValue at 0x0000025041DF5E50>
                └ <google.protobuf.internal.type_checkers.Int32ValueChecker object at 0x0000025041DFCAC0>

  File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\google\protobuf\internal\type_checkers.py", line 171, in CheckValue
    raise TypeError(message)
                    └ "None has type <class 'NoneType'>, but expected one of: (<class 'int'>,)"

TypeError: None has type <class 'NoneType'>, but expected one of: (<class 'int'>,)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000025040F82DC0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 46504)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x0000025040F82AF0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 46504)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 46504)>
    │    │        │    └ (<weakref at 0x00000250430020E0; to 'ThreadPoolExecutor' at 0x0000025042E8A5E0>, <_queue.SimpleQueue object at 0x0000025042E8...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 46504)>
    │    └ <function _worker at 0x0000025042E7FAF0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 46504)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x0000025042E7FC10>
    └ <concurrent.futures.thread._WorkItem object at 0x0000025042EDE1F0>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x0000025042EDE1F0>
             │    │   │    └ [<grpc._cython.cygrpc.RequestCallEvent object at 0x0000025041CEB900>, <grpc._server._RPCState object at 0x0000025042EDEDF0>, ...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x0000025042EDE1F0>
             │    └ <function _unary_response_in_pool at 0x0000025042EC6550>
             └ <concurrent.futures.thread._WorkItem object at 0x0000025042EDE1F0>

  File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 552, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method GoodsServicer.GetAllCategorysList of <goods_srv.handler.goods.GoodsServicer object at 0x0000025042E9EA30>>
                        │              │          └ <grpc._server._RPCState object at 0x0000025042EDEDF0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x0000025041CEB900>
                        └ <function _call_behavior at 0x0000025042EC6160>

> File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x0000025043003400>
                           │        └ 
                           └ <bound method GoodsServicer.GetAllCategorysList of <goods_srv.handler.goods.GoodsServicer object at 0x0000025042E9EA30>>

  File "C:\Users\Administrator\PycharmProjects\mxshop_srvs\goods_srv\handler\goods.py", line 254, in GetAllCategorysList
    category_rsp.parentCategory = category.parent_category_id
    │            │                │        └ <peewee.ObjectIdAccessor object at 0x00000250420F19A0>
    │            │                └ <Category: 130358>
    │            └ <google.protobuf.internal.python_message._FieldProperty object at 0x0000025041E66BD0>
    └ id: 130358
      name: "\346\226\260\351\262\234\346\260\264\346\236\234"

  File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\google\protobuf\internal\python_message.py", line 715, in field_setter
    raise TypeError(

TypeError: Cannot set CategoryInfoResponse.parentCategory to None: None has type <class 'NoneType'>, but expected one of: (<class 'int'>,)
2020-10-01 00:01:51.926 | INFO     | __main__:on_exit:27 - 注销 bc00fd35-0335-11eb-9e0d-40b0760ebfa7 服务
2020-10-01 00:01:51.931 | INFO     | __main__:on_exit:29 - 注销成功
