2020-10-01 00:05:57.032 | INFO     | __main__:serve:85 - 启动服务: 192.168.1.102:57825
2020-10-01 00:05:57.039 | INFO     | __main__:serve:88 - 服务注册开始
2020-10-01 00:05:57.048 | INFO     | __main__:serve:95 - 服务注册成功
2020-10-01 00:06:01.970 | ERROR    | grpc._server:_call_behavior:435 - An error has been caught in function '_call_behavior', process 'MainProcess' (16212), thread 'ThreadPoolExecutor-0_0' (40040):
Traceback (most recent call last):

  File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\google\protobuf\internal\python_message.py", line 713, in field_setter
    new_value = type_checker.CheckValue(new_value)
                │            │          └ None
                │            └ <function IntValueChecker.CheckValue at 0x0000022EBF7F6E50>
                └ <google.protobuf.internal.type_checkers.Int32ValueChecker object at 0x0000022EBF7FDA90>

  File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\google\protobuf\internal\type_checkers.py", line 171, in CheckValue
    raise TypeError(message)
                    └ "None has type <class 'NoneType'>, but expected one of: (<class 'int'>,)"

TypeError: None has type <class 'NoneType'>, but expected one of: (<class 'int'>,)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000022EBE982DC0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 40040)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x0000022EBE982AF0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 40040)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 40040)>
    │    │        │    └ (<weakref at 0x0000022EC09F7630; to 'ThreadPoolExecutor' at 0x0000022EC007AF70>, <_queue.SimpleQueue object at 0x0000022EC008...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 40040)>
    │    └ <function _worker at 0x0000022EC0090430>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 40040)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x0000022EC0090550>
    └ <concurrent.futures.thread._WorkItem object at 0x0000022EC08E0790>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x0000022EC08E0790>
             │    │   │    └ [<grpc._cython.cygrpc.RequestCallEvent object at 0x0000022EBF6EA810>, <grpc._server._RPCState object at 0x0000022EC08D4D90>, ...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x0000022EC08E0790>
             │    └ <function _unary_response_in_pool at 0x0000022EC08C2EE0>
             └ <concurrent.futures.thread._WorkItem object at 0x0000022EC08E0790>

  File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 552, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method GoodsServicer.GetAllCategorysList of <goods_srv.handler.goods.GoodsServicer object at 0x0000022EC009E460>>
                        │              │          └ <grpc._server._RPCState object at 0x0000022EC08D4D90>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x0000022EBF6EA810>
                        └ <function _call_behavior at 0x0000022EC08C2AF0>

> File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\grpc\_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x0000022EC08E0940>
                           │        └ 
                           └ <bound method GoodsServicer.GetAllCategorysList of <goods_srv.handler.goods.GoodsServicer object at 0x0000022EC009E460>>

  File "C:\Users\Administrator\PycharmProjects\mxshop_srvs\goods_srv\handler\goods.py", line 266, in GetAllCategorysList
    category_rsp.parentCategory = category.parent_category_id
    │            │                │        └ <peewee.ObjectIdAccessor object at 0x0000022EBFAF19A0>
    │            │                └ <Category: 130358>
    │            └ <google.protobuf.internal.python_message._FieldProperty object at 0x0000022EBF866AE0>
    └ id: 130358
      name: "\346\226\260\351\262\234\346\260\264\346\236\234"

  File "C:\Users\Administrator\Envs\mxshop_srv\lib\site-packages\google\protobuf\internal\python_message.py", line 715, in field_setter
    raise TypeError(

TypeError: Cannot set CategoryInfoResponse.parentCategory to None: None has type <class 'NoneType'>, but expected one of: (<class 'int'>,)
2020-10-01 00:07:47.627 | INFO     | __main__:on_exit:26 - 注销 d322e44b-0336-11eb-a452-40b0760ebfa7 服务
2020-10-01 00:07:47.633 | INFO     | __main__:on_exit:28 - 注销成功
